### ISSUE TITLE
Города импортнулись в неправильной кодировке

### ISSUE THREAD

**Issue by Svoka** [m-messiah/ip2geo#1]
вот такой вид: 

109.105.128.0-109.105.151.255 0JzQvtGB0LrQstCw;
109.105.160.0-109.105.163.0 0KLRjtC80LXQvdGM;
109.105.163.1-109.105.163.255 0JzQvtGB0LrQstCw;
109.105.164.0-109.105.191.255 0KLRjtC80LXQvdGM;
109.105.64.0-109.105.95.255 0JzQtdC20LTRg9GA0LXRh9C10L3RgdC6;
109.106.128.0-109.106.159.255 0JLQvtGA0L7QvdC10LY=;
109.106.192.0-109.106.199.255 0JrRgNCw0YHQvdC+0LTQsNGA;
109.106.200.0-109.106.205.255 0JLQvtC70LPQvtC00L7QvdGB0Lo=;
109.106.206.0-109.106.206.127 0JDRgdGC0YDQsNGF0LDQvdGM;
109.106.206.128-109.106.206.255 0JzQvtGB0LrQstCw;
109.106.207.32-109.106.207.47 0JzQvtGB0LrQstCw;
109.106.207.48-109.106.209.255 0KDQvtGB0YLQvtCyLdC90LAt0JTQvtC90YM=;
109.106.211.0-109.106.211.255 0KHRgtCw0LLRgNC+0L/QvtC70Yw=;
109.106.212.0-109.106.212.255 0JzQvtGB0LrQstCw;
109.106.213.0-109.106.213.255 0KDQvtGB0YLQvtCyLdC90LAt0JTQvtC90YM=;
109.106.214.0-109.106.214.15 0JrRgNCw0YHQvdC+0LTQsNGA;
109.106.214.16-109.106.214.255 0JzQvtGB0LrQstCw;
109.106.216.0-109.106.218.255 0K3Qu9C40YHRgtCw;
109.106.222.0-109.106.223.255 0KDQvtGB0YLQvtCyLdC90LAt0JTQvtC90YM=;
109.107.160.0-109.107.161.255 0JzQvtGB0LrQstCw;
109.107.162.0-109.107.167.255 0JvQvtCx0L3Rjw==;
109.107.168.0-109.107.169.255 0J7QtNC40L3RhtC+0LLQvg==;
109.107.170.0-109.107.171.255 0JzQvtGB0LrQstCw;
109.107.172.0-109.107.175.255 0JvQvtCx0L3Rjw==;
109.107.176.0-109.107.191.255 0JzQvtGB0LrQstCw;
109.108.32.0-109.108.63.255 0JjQstCw0L3QvtCy0L4=;
109.109.208.0-109.109.217.7 0JLQu9Cw0LTQuNCy0L7RgdGC0L7Qug==;
109.109.217.112-109.109.217.143 0JLQu9Cw0LTQuNCy0L7RgdGC0L7Qug==;

**Comment by m-messiah** [comment]
А что здесь неправильно? base64 от города, как и должно быть.

**Comment by Svoka** [comment]
Понял
