### ISSUE TITLE
Не geoip, а просто geo

### ISSUE THREAD

**Issue by Nabu-thinker-ru** [m-messiah/ip2geo#1]
Судя по примеру конфига вы преобразуете в формат доступный для http://nginx.org/ru/docs/http/ngx_http_geo_module.html
а не для http://nginx.org/ru/docs/http/ngx_http_geoip_module.html

например, в моем случае это критично потому что второй можно доставить из epel, а для первого нужно пересобрать nginx

**Comment by m-messiah** [comment]
Совершенно верно, это видно и из названия. Опечатку в README поправил, спасибо.

geoip модуль заточен под определенный вид бинарных баз, поэтому внедрять его поддержку не планирую, а geo замечательный.
