### ISSUE TITLE
опционально, генерировать в utf8  (или  latin1), без base64

### ISSUE THREAD

**Issue by chipitsine** [m-messiah/ip2geo#12]
Макс, привет. 

столкнулся с задачкой (хотелось города для англ. языка)

`./ip2geo -maxmind -lang en`

можно добавить ключ, по которому кодировка оставалась оригинальная ? (ну или приводилась бы к latin1, если несложно)

**Comment by m-messiah** [comment]
Сделал ключ `-nobase64` для пропуска трансформации. 
Зарелизил в v1.0.5 (Внимание - там к бинарнику дописал платформу)

**Comment by chipitsine** [comment]
круто. спасибо
