### ISSUE TITLE
заключение в кавычки

### ISSUE THREAD

**Issue by chipitsine** [m-messiah/ip2geo#17]
при использовании аргументов "-nobase64 -lang en" страны иногда получаются с пробелами (возможно, города тоже ?)

United States --> "nginx: [emerg] invalid number of the geo parameters in "

если заключить "United States" в кавычки, то ок.

**Comment by chipitsine** [comment]
travis это пропустил, потому что в travis не проверяется --nobase64 ?

**Comment by m-messiah** [comment]
Добавил кавычки в https://github.com/m-messiah/ip2geo/releases/tag/v1.0.7
