### ISSUE TITLE
город с кавычкой

### ISSUE THREAD

**Issue by chipitsine** [m-messiah/ip2geo#19]
привет

https://travis-ci.com/chipitsine/ip2geo/jobs/194246158#L756

```77.40.108.0-77.40.111.255 "Novyy Tor"yal";```

я, честно, не знаю как это правильно экранировать.
добавим тест в .travis.yml ? 

на скорую руку набросал https://github.com/chipitsine/ip2geo/commit/fba084d0381bae543d06482c21ef8d9a813c47af

**Comment by m-messiah** [comment]
Привет.
Увидел, этот город есть в ipv4, но нет в ipv6, так что да, надо по-отдельности тестировать. 

Насчет кавычек - можно явно их вырезать, либо заменять на что-нибудь (`\"` или `'` (надо посмотреть на восприятие nginx))
Посмотрю на выходных
