### ISSUE TITLE
возможность импорта платных баз

### ISSUE THREAD

**Issue by chipitsine** [m-messiah/ip2geo#21]
привет!

есть фича реквест, хочется использовать платную PX4 базу ip2location.
можно такое запилить ?

у меня навскидку есть мысль, что, возможно, стоит добавить возможность указывать в качестве источника уже скаченную базу

**Comment by m-messiah** [comment]
Запилить-то все можно. Тут уже в принципе есть интерфейс [GeoBase](https://github.com/m-messiah/ip2geo/blob/master/common_geobase.go#L15-L22) так что добавление новой базы - это лишь его реализация, плюс добавление соответствующих флагов в [app.go](https://github.com/m-messiah/ip2geo/blob/master/app.go)

Например, можно в интерфейсе вместо скачивания ничего не делать и сразу считывать по данному пути из флага. Но тут еще нужно знать формат базы, чтобы аккуратно прочитать, поэтому я бы сходу не подписался такое делать, потому что у меня этой базы нет.

**Comment by chipitsine** [comment]
могу дать базу

**Comment by m-messiah** [comment]
Если нет желания самостоятельно делать или нет иных заинтересованных - скинь на почту базу (или еще куда). Попробую, как время будет.

**Comment by chipitsine** [comment]
Знал бы голанг, сделал бы))

Какой адрес почты?

**Comment by m-messiah** [comment]
m.muzafarov@gmail.com

**Comment by m-messiah** [comment]
Посмотрел на базу - она точно такая же как и lite, просто немного другие имена файлов. 

Сделал для нее просто дополнительное ветвление в коде lite - https://github.com/m-messiah/ip2geo/pull/22

Скачивание этой базы как-то сложно происходит или так же как lite - по токену? А то может и скачивание тоже тут оставить?

**Comment by m-messiah** [comment]
@chipitsine там в базе есть разные типы прокси: PUB/DCH/e.t.c. - это кому-нибудь нужно или достаточно так же 1 или 0?

**Comment by chipitsine** [comment]
да, как раз хотел про это сказать. отличие бесплатной от платной в том, что в бесплатной только один тип прокси. 0 или 1 скорее всего недостаточно

**Comment by chipitsine** [comment]
скачивание так же, по токену
