### ISSUE TITLE
Добавить чтение из конфигурационного файла

### ISSUE THREAD

**Issue by m-messiah** [m-messiah/ip2geo#25]
Добавить флаг для пути до конфига и описывать все модули и их использование там, а то флагов стало слишком много

**Comment by chipitsine** [comment]
зачем ? с флагами идеально

**Comment by m-messiah** [comment]
Сейчас без хэлпа сложно понять, какой флаг к чему относится. Плюс светить токены в параметрах считается плохим тоном, лучше уж в файлик вписать, до которого доступ будет только у нужного пользователя

**Comment by chipitsine** [comment]
![Screenshot from 2019-06-14 11-34-41](https://user-images.githubusercontent.com/2217296/59488256-82138000-8e98-11e9-8fd7-e87ee953f813.png)

я бы, честно, вложился в популяризацию и, возможно, монетизацию.
штука крутая, но не очень раскрученная

светить токены в параметрах - норм практика
