### ISSUE TITLE
Changes to GeoLite2 license and distribution require changes to how you download databases

### ISSUE THREAD

**Issue by 2shortplanks** [m-messiah/ip2geo#31]
The [URL](https://github.com/m-messiah/ip2geo/blob/7efb50e3e641643314f73243ddeef2b3ece56728/maxmind.go#L33) used to directly download GeoLite2 databases will no longer function after December 30th 2019.

Due to upcoming data privacy regulations, MaxMind are making significant changes to how users access free MaxMind GeoLite2 databases starting December 30, 2019. The databases will continue to be available without charge and for redistribution. However, you will be required to create an account and use a license key to download the databases, and agree to a new EULA that addresses applicable data privacy regulations.

Learn more on the MaxMind blog: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/.

Mark Fowler
MaxMind

**Comment by m-messiah** [comment]
Thank you @2shortplanks, I have updated the tool - new scheme is available at [version 1.1.4](https://github.com/m-messiah/ip2geo/releases/tag/v1.1.4)
