### ISSUE TITLE
$city_mm и пр. как значения переменных

### ISSUE THREAD

**Issue by achekalin** [m-messiah/ip2geo#7]
Странно, но на nginx 1.13.6 наблюдаю картину: при использовании предложенной конфиги переменные в полях default не заменяются их значениями, а отдаются "как строки". Т.е., скажем, фрагмент конфига:
```
    geo $city {
        ranges;
        default $city_mm;
        include geo/db/city.txt;
    }
```
(если не находит данных в словаре city.txt) отдаст не значение переменной с именем city_mm, а именно строчку "$city_mm".
Сложно проверить, зависит ли это поведение от версии nginx, и когда началось, но, как факт, оно существует.

**Comment by m-messiah** [comment]
Верно, они стали строже соответствовать своей документации и теперь в результате geo можно только строку(((
Зато обычные map так умеют по документации.
Навскидку, есть идея сделать map вроде такого:
```nginx
geo $city_geo {
    ranges;
    include geo/city.txt;
}

geo $city_mm {
    ranges;
    include geo/mm_city.txt;
}

map $city_geo $city {
	"" $city_mm;
	default $city_geo;
}
```

**Comment by achekalin** [comment]
Да, вы правы, так заработало, и именно так, если подумать, и правильно сделать. Хотя вывод строки вместо значения одноименной переменной напрямую ни подтвержден, ни опровергнут в документации. 

Сделал так:
```
# Region
    geo $region {
        ranges;
        include geo/db/region.txt;
    }
# City
    geo $city_geo {
        ranges;
        include geo/db/city.txt;
    }

    geo $city_mm {
        ranges;
        include geo/db/mm_city.txt;
    }

    map $city_geo $city {
        "" $city_mm;
        default $city_geo;
    }
# TZ
    geo $tz_geo {
        ranges;
        include geo/db/tz.txt;
    }

    geo $tz_mm {
        ranges;
        include geo/db/mm_tz.txt;
    }

    map $tz_geo $tz {
        "" $tz_mm;
        default $tz_geo;
    }
# Tor
    geo $is_tor {
        ranges;
        default 0;
        include geo/DB/tor.txt;
    }
```

Ну и 
```
mkdir -p /etc/nginx/geo/db && /etc/nginx/geo/ip2geo -output /etc/nginx/geo/output && mv /etc/nginx/geo/db /etc/nginx/geo/db.old && mv /etc/nginx/geo/output /etc/nginx/geo/db && rm -rf /etc/nginx/geo/db.old && /bin/systemctl reload nginx.service
```
в crontab, чтобы "поатомарнее" обновлялось.

**Comment by chipitsine** [comment]
чтобы "атомарнее", еще стоит предусмотреть "nginx -t", и откат обратно, если не прошла валидация. ну и, reload вместо restart лучше в том плане, что текущие запросы не рвутся

**Comment by achekalin** [comment]
@chipitsine nginx -t при обновлении данных гео-баз не поможет :) он не проверяет целостность данных в них. А вот про reload да, в комменте выше я поправил - у меня просто это была не вся логика ночного обновления, мне, в моем случае, restart актуальнее был.

В любом случае, спасибо @m-messiah за подсказку с map, она отлично работает. Будет возможность - вынести бы этот конфиг в README.md, наверняка кому-то ещё пригодится!
