### ISSUE TITLE
сломался ipgeobase

### ISSUE THREAD

**Issue by chipitsine** [m-messiah/ip2geo#8]
есть предложение посмотреть в сторону того, чтобы рассматривать эту ошибку нефатальной

а) использовать предыдущую базу ?
б) использовать только maxmind ?

```
ip2geo -output /usr/local/etc/geo
           | Use output directory                                         [/usr/local/etc/geo]
TOR        | Blutmagie Download                                           [OK]
TOR        | Torproject Download                                          [OK]
TOR        | Merge                                                        [OK]
TOR        | Write nginx maps                                             [OK]
MaxMind    | Download                                                     [OK]
MaxMind    | Unpack                                                       [OK]
MaxMind    | Generate cities                                              [OK]
IPGeobase  | Download no answer                                           [FAIL]
IPGeobase  | Download: Get http://ipgeobase.ru/files/db/Main/geo_files.zip: dial tcp 194.85.91.253:80: i/o timeout [FAIL]
ERROR: Job failed: exit status 1
```

но есть и плюсы - мы узнали, что ipgeobase сломался ))

**Comment by m-messiah** [comment]
Сложный вопрос. 
Фактически, если указано, что хочешь базу ipgeobase, а он сломался, то это фатальная ошибка. Запуск без аргументов автоматически означает "использовать все аргументы".
Так что считать её нефатальной будет идеологически неправильно и будет запутывать (вы бы тогда так и не узнали, что ipgeobase сломался и что файлы генерации неполные)

а) ip2geo ничего не знает о путях до предыдущей базы.
б) можно, достаточно указать аргументы явно `ip2geo -maxmind -tor -output /usr/local/etc/geo`

**Comment by chipitsine** [comment]
с тем, что полезно узнавать о фатальных ошибках - согласен.

насчет остального стоит подумать. кажется, что гео-базы это такая предметная область, когда "чуть-чуть старые данные - в принципе ок"
